# -*- coding: utf-8 -*-
"""task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jg0gPw0lMY0BRmRTm3z4Y7yrCewvlE-e
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind

# Load Excel file
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

# Display first 5 rows
print(df.head())

# Remove missing values
df = df.dropna()

# Select only numeric columns
numeric_cols = df.select_dtypes(include='number').columns

print("Numeric Columns:", list(numeric_cols))

# Perform T-Test if at least 2 numeric columns exist
if len(numeric_cols) >= 2:
    col1 = numeric_cols[0]
    col2 = numeric_cols[1]

    t_stat, p_value = ttest_ind(df[col1], df[col2])

    print(f"\nComparing: {col1} vs {col2}")
    print("T-Statistic:", t_stat)
    print("P-Value:", p_value)

    if p_value < 0.05:
        print("Result: Statistically Significant")
    else:
        print("Result: Not Statistically Significant")
else:
    print("Not enough numeric columns for T-Test.")

# Histogram
df[numeric_cols[0]].plot(kind='hist', bins=20)
plt.title(numeric_cols[0])
plt.show()

# Correlation Matrix
corr = df[numeric_cols].corr()

plt.figure(figsize=(8,6))
plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Correlation Matrix")
plt.show()